### ISSUE TITLE
More Buttons for switching Network

### ISSUE THREAD

**Issue by dc7jzb** [dg9vh/MMDVMHost-Dashboard#133]
Hi Kim,
Is there a way to get more Buttons for Networkswitching ?

This will be Interesting for switching between DMR Masters for Testing, or switching to a HBLink Network. 

73 de Mario, DC7JZB

**Comment by dg9vh** [comment]
Hi Mario,
actually I am thinking about a concept to realize such things, this also goes together with https://github.com/dg9vh/MMDVMHost-Dashboard/issues/130 because switching to single-mode is similar to switching networks by changeing MMDVM.ini... I am looking for ideas how to do it in User-Interface (Dashboard-view) and how to configure it (for example within setup.php). 
Actually I am a bit handicapt by a "Kehlkopfentzündung" but I think, I would find a concept for realizing this. Maybe it would end in a list-box where to chose a concrete (user-defined) situation to switch to. 

All following to this see https://github.com/dg9vh/MMDVMHost-Dashboard/issues/130

**Comment by dc7jzb** [comment]
Na dann mal gute Besserung ;)
