### ISSUE TITLE
ircddbgateway running, but dash says NO !

### ISSUE THREAD

**Issue by iw9grl** [dg9vh/MMDVMHost-Dashboard#153]
Hi 
I don't understand why, in the config file the Dstar setting is done but I have alsways : 

![image](https://user-images.githubusercontent.com/16877668/27003459-28d74e4c-4df7-11e7-9034-e58c0fd1b6d7.png)

![image](https://user-images.githubusercontent.com/16877668/27003463-3de72a96-4df7-11e7-899d-39315f4be891.png)

I tried also with ircddbgateway  (withoud d ) but nothing change .

Do you have any idea ?
thank you
regards

**Comment by dg9vh** [comment]
@iw9grl seems you did not activate dstar in MMDVM.ini?

**Comment by iw9grl** [comment]
yes it is active

![image](https://user-images.githubusercontent.com/16877668/27005593-04aac442-4e22-11e7-8289-54569c9615cd.png)

**Comment by dg9vh** [comment]
How about dstar network?

**Comment by iw9grl** [comment]
It is active !

**Comment by dg9vh** [comment]
do you have a public link to the dashboard to see the tool-tip?

**Comment by iw9grl** [comment]
Sure
http://iw9grl.dyndns.org:82/dash/

**Comment by dg9vh** [comment]
If you move the mouse over the grey label of DSTAR Network you become a message, that you have configured a remote gateway, so this could not be checked. This means:your gateway-address in the dstar-network-section differs from "localhost". If you are running the ircddbgateway at the same host as the dashboard is running (and where the MMDVMHost is running) you should use localhost instead of any IP-addresses from local lan... is there a special cause, you configured it other way?

**Comment by iw9grl** [comment]
Oook, yes I use the local-ip because I configured two modules. I will try to use localhost instead. Thanks

**Comment by dg9vh** [comment]
closed because it's working now
