### ISSUE TITLE
Raspberry Pi 4 B apache2 php8 issues

### ISSUE THREAD

**Issue by jjalbert73** [dg9vh/MMDVMHost-Dashboard#223]
Not sure if this is me or the scrips in this project, but I was playing with a Pi Zero W and PiOS Bookworm and was able to get a mmdvmhost running great. Than I added Apache2 and php and got the dashboard running great. Now I am playing with a PI 4, running bookworm lite 32 bit, and when I try to get the dashboard going, i get a 500 error on the index.php, and if I go direct to setup.php it only loads a very small portion of the page. The apache log show errors in the php script(sorry i am at work and do not have the errors but can post later). I don't know if the script does not work on php8.x or if it is something I did. I have changed file permissions, and done a full purge and reinstall of apache and php. If I create a test.php file and put a script to echo hello world it works fine. Anyone have any thoughts on this?

**Comment by hb9eue** [comment]
Yes, I read, code is not maintained anymore. But maybe somebody knows the solution.

I have the same issue after upgrading my raspberry, upgrading to the last git release of MMDVMHost-Dashboard and switching to php8.

setup.php loads, but there is no save button, premissions look right, my previous config.php does not seem to be valid anymore.

**Comment by hb9eue** [comment]
On if the issues is in tools.php where the constant DISTRIBUTION has to be quoted, like defined("DISTRIBUTUON") instead of defined(DISTRIBUTION).
Now the pages show  some infos, still not correctly formated, still many errors regarding accessing arrays, bot at least, something is shown.
Also setup.php does not work at all. I had to more or less start by checking what constants need to exist and setting them manually in config.php
