### ISSUE TITLE
Active modes green/red/grey don't work properly

### ISSUE THREAD

**Issue by iw9grl** [dg9vh/MMDVMHost-Dashboard#37]
Hi

The following issues are referred ONLY if MMDVMHost is not running by systemctl !!

I noticed that if disabled System Fusion by MMDVM.ini, in the dashboard the System Fusion become grey

But If for example,  I put the DMR enable = 0 in MMDVM.ini, running the MMDVMHost in the dashboard I see that it is enabled, the same for DSTAR enable = 0 and if I disable one timeslot, all remain green.

The only situation that all become RED is if I stop the MMDVMHost process .
Could you verify please ?

73 de IW9GRL

**Comment by dg9vh** [comment]
Hi,

you allways have to take a look at both components in MMDVM.ini: the mode itself and the networking-component. All the magic happens in function showMode($mode, $mmdvmconfigs), here depending on the mode (DSTAR network is checked separately from others, because of the dependency to the ircddbgateway, to make it perfect, it should also include YSF network, because this regularly depends on YSFGateway but actually not implemented) the configuration and availablility of the corresponding process is checked.

So if you put DMR on 0 but leave DMR Network on 1, it is logically so, that DMR would be grey but Network stays green, because the MMDVMHost still is linked to the Master.

If you disable only one timeslot (or both) but leave DMR Network enabled, you only see the grey buttons on the timeslot-buttons but not on the Network...

I my eyes everything works ok. 

Maybe there is an issue with browser-cache? Did you clean up the temporary internet files or browser-cache?

**Comment by iw9grl** [comment]
Hi 

thank you for your answer .
All works as you said only if MMDVHost run by systemctl, but if you try to run the MMDVMHost by hand running : sudo  ./blabla/MMDVMHost  ./bbbb/MMDVM.ini  and in the ini file you have for example put to ZERO DMR mode and DMR network, or changing only a timeslot value, it doesn change in the dashboard.

thank you
73

**Comment by dg9vh** [comment]
Sorry, I can't confirm that. The dashboard checks first the Enabled-state in the MMDVM.ini-file and if enabled it checks with pgrep <programname>, if the MMDVMHost or the ircddbgateway(d) is running and if this is running, it shows green, if not, it is red, if disabled, it is grey whether the corresponding process is running or not.

Do you really use the same MMDVM.ini-file by calling MMDVMHost as configured in the config.php of the dashboard?

**Comment by iw9grl** [comment]
Hi Kim
really sorry, I changed the ini file name ........ MY MISTAKE !!!! 
thank you for your kindly support ......

**Comment by dg9vh** [comment]
No problem :-) I am allways trying to find the source of the problem... your issue gave me the point to keep the YSFGateway in mind like the ircddbgateway... so this would be one thing to be implemented next...

**Comment by iw9grl** [comment]
Thank you again .... best regards
