### ISSUE TITLE
Show DMR-IDs additionally

### ISSUE THREAD

**Issue by dg9vh** [dg9vh/MMDVMHost-Dashboard#45]
To be configured in setup.php: Show DMR-IDs and Callsigns. Needs to switch off name-resolution in MMDVM.ini.

**Comment by pjao** [comment]
Hi,

With the last update DMR-IDs are not name resolved by MMDVMHost, so on the Dashboard only appears numbers. Is it related?

Could be a condition? If on the log there is no name-resolution, than try to find by Dashboard...

**Comment by dg9vh** [comment]
This is a bug that already has been fixed in MMDVMHost. Just do a gut pull again.

**Comment by pjao** [comment]
Nop, the bug is there again with the last pull of P25. 

It seams it is not loading DMR Ids to the callsign lookup table.

M: 2016-09-29 10:25:01.797 DMR Slot 2, received network voice header from 2682044 to TG 9
M: 2016-09-29 10:25:02.388 DMR Slot 2, received network end of voice transmission, 0.5 seconds, 0% packet loss, BER: 0.0%
M: 2016-09-29 10:29:30.414 DMR Slot 2, received network voice header from 2682040 to TG 9
M: 2016-09-29 10:29:31.378 DMR Slot 2, received network end of voice transmission, 0.8 seconds, 0% packet loss, BER: 0.0%

**Comment by dg9vh** [comment]
Please forward your issue to jonathan, g4klx. Tnx.

**Comment by pjao** [comment]
Done, and again working...

**Comment by phl0** [comment]
I just pulled the latest commit from G4KLX repo. DMR ID lookup is working:

```
M: 2016-09-29 13:35:03.541 CSBK BS_Dwn_Act for ANY received from DF2ET
M: 2016-09-29 13:35:03.921 DMR Slot 2, received RF voice header from DF2ET to TG 9
M: 2016-09-29 13:35:06.619 DMR Slot 2, received RF end of voice transmission, 2.5 seconds, BER: 1.4%
```

Version:

```
$ git log | head
commit a91b5786ee3457d9dfd2331089fd316b537c049e
Merge: 0306659 157bc8c
Author: Jonathan Naylor <naylorjs@yahoo.com>
Date:   Thu Sep 29 13:00:27 2016 +0100

    Merge pull request #163 from phl0/dev

    Disable networks by default or if missing in MMDVM.ini

commit 157bc8c058c244553329ec972a241079bf510f13
```
