### ISSUE TITLE
Bug in Currently TXing / Zombie...

### ISSUE THREAD

**Issue by faxe2110** [dg9vh/MMDVMHost-Dashboard#55]
Please take a look on this screenshot. Maybe it´s a bug in "Currently TXing"

73
SA7BNT
Tim
![bildschirmfoto 2016-10-27 um 10 55 54](https://cloud.githubusercontent.com/assets/7265595/19761249/5a1368fc-9c35-11e6-9453-8b179a483981.png)

**Comment by dg9vh** [comment]
M: 2016-10-27 08:48:20.509 DMR Slot 1, received network data header from EA3FEJ to TG 92, 5 blocks
M: 2016-10-27 08:48:22.138 DMR Slot 1, network watchdog has expired
M: 2016-10-27 08:50:22.491 DMR Slot 1, received network data header from EA3FEJ to TG 92, 5 blocks
M: 2016-10-27 08:50:24.123 DMR Slot 1, network watchdog has expired
M: 2016-10-27 08:52:25.222 DMR Slot 1, received network data header from EA3FEJ to TG 92, 5 blocks
M: 2016-10-27 08:52:26.837 DMR Slot 1, network watchdog has expired
M: 2016-10-27 08:54:26.684 DMR Slot 1, received network data header from EA3FEJ to TG 92, 5 blocks
M: 2016-10-27 08:54:28.320 DMR Slot 1, network watchdog has expired

**Comment by phl0** [comment]
What is the issue here?

**Comment by dg9vh** [comment]
@phl0 I think it is only an optical thing: If you are sending data (SMS or other) each data-packet is listed in the logfile and therefore listed in the dashboard...

It is a low-level-issue with lower priority and I am not shure, if it is necessary to do anything here - because it is correct, there are several transmissions... may we close it, to get rid of it...

It's philosophically...

**Comment by pjao** [comment]
Trying to fix it with https://github.com/dg9vh/MMDVMHost-Dashboard/pull/103
