### ISSUE TITLE
error when opening dashboard 

### ISSUE THREAD

**Issue by scotta1980** [dg9vh/MMDVMHost-Dashboard#59]
i am getting these errors when opening the dashboard i have tryed it on two different browsers still the same  

DataTables warning: table id=localTx - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1
and this error 
DataTables warning: table id=lastHeard - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

**Comment by dg9vh** [comment]
First of all: Try to clean browser cache and retry.
Then: If still exists, could you provide Dashboard-URL? Maybe via email (dg9vh@darc.de)?

**Comment by pjao** [comment]
I've experienced the same problem, that was due to update the dashboard without refreshing the browser or/and the webserver.

As Kim - DG9VH said, you could clean browser cache, stop webserver, let the browser give the connection error, start again the webserver and refresh.

With me that solve the problem.

Paulo - CT2JAY

**Comment by dg9vh** [comment]
He reverted to last known good version... don't have a clue, why this error is comming up.
