### ISSUE TITLE
Issue with DMRIDUpdate.sh

### ISSUE THREAD

**Issue by danielharrelson** [dg9vh/MMDVMHost-Dashboard#79]
Line 93 has:

curl 'http://www.dmr-marc.net/cgi-bin/trbo-database/datadump.cgi?table=users&format=csv&header=0' 2>/dev/null | awk -F"," '{printf "%s\t%s\t%s\n", $1, $2, $4 == "" ? $3 : $4}' | sed -e 's/\(.\) .*/\1/g' > ${DMRIDFILE}

it should be

curl 'http://www.dmr-marc.net/cgi-bin/trbo-database/datadump.cgi?table=users&format=csv&header=0' 2>/dev/null | awk -F"," '{printf "%s\t%s\t%s\n", $1, $2, $4 == "" ? $3 : $3}' | sed -e 's/\(.\) .*/\1/g' > ${DMRIDFILE}

Otherwise it is just showing up the "City" under the "Name" column.

**Comment by dg9vh** [comment]
Hi,

This script is not part of this project. Please file the issue into the correct project.

Tnx

**Comment by phl0** [comment]
I am just investigating and cannot see an error. Could you please paste an example?
Besides this: The script is part of MMDVMHost so the issue should be filed for that project.

**Comment by phl0** [comment]
Although its closed here: I reworked the command. See: https://github.com/g4klx/MMDVMHost/pull/248

**Comment by g0wfv** [comment]
@danielharrelson, good catch on the script breaking!

For info - The issue was the format of the datadump has changed (when, I don't know!) to omit the "Nickname" field that was previously at field 3 in the generated CSV.  This bumped the "Full Name" which was at field 4 to field 3 and the "City" from 5 to 4.  Unfortunately, this caused the error you saw.  Incidentally, I just checked my DMRIds.dat file, and have the same issue, but as I don't use the dashboard, didn't notice as the Host software doesn't use the name field in the file!

@phl0 has fixed the script in the main MMDVMHost project (thanks, Flo!) and all should be good.  Although I can now see the trailing spaces he mentioned to me - they seem to have been eradicated!  Seems someone in Europe has been playing and mucked the database up a bit by stripping middle and last names incorrectly - All other areas (Americas, Australia, NZ etc) all seem to be fine!

If the script breaks again, feel free to report it [here](https://github.com/g4klx/MMDVMHost/issues) as I don't subscribe to issues in the Dashboard project, but I do the main Host project!

73,
Tony G0WFV
