### ISSUE TITLE
DSTAR 'target' spaces aren't correctly displayed 

### ISSUE THREAD

**Issue by m1geo** [dg9vh/MMDVMHost-Dashboard#80]
On DSTAR, a target such as '       E' for echo test doesn't display right. The previous spaces are lost in the HTML.

These should be '&nbsp;'  to protect the spaces. 

Just something I noticed. 

George M1GEO.

**Comment by m1geo** [comment]
Turns out that github also removes them! 

'^^^^^^^E' where the carrat is a space. 

And, replace with '& n b s c' 

George. M1GEO.

**Comment by phl0** [comment]
I currently cannot produce a log line by myself. Could you mail me one
or make a screenshot pls?

**Comment by phl0** [comment]
Made a small patch https://github.com/phl0/MMDVMHost-Dashboard/tree/devel to remove this. However due to not using a fixed width font this looks somewhat odd:

![screenshot from 2017-01-16 18-13-21](https://cloud.githubusercontent.com/assets/7112907/21992815/3d972cfe-dc18-11e6-8dfb-361f2276ae5d.png)

I'll try a give it a go with a Courier font or the like.

**Comment by dg9vh** [comment]
Should we give text-align: right as style-element a try to make the cell right aligned?

**Comment by phl0** [comment]
That would on the other hand look if you have a short callsign like yours or my one I guess because the left part should be left aligned.

**Comment by dg9vh** [comment]
@m1geo I do not really get the point, why it is necessary to display those information with 7 spaces in front of it? I think everybody who uses DSTAR know, that such commands are placed in the 8th position of the URCALL-Field so on the dashboard, that is for information purpose, in my eyes it is not necessary to follow all special needs, "the system" has to use... the 8th place is only relevant because the system does not take care about the first 7 positions... it's "per definition" to place commands on position 8...

@phl0 you are right... my idea was only to right align such special commands like E, I and U. But this is another problem that brings some ugly optic on the right border...

The problem could be solved by using a  fixed width font... and replacing each space with a non breaking space... but this is another optical issue then... other font means other optical look and feel...

**Comment by phl0** [comment]
Me thinks about giving a fixed-width font a try and then see what it looks like. It would make it easier to distinguish between E as command and someone using E as a callsign (which of course is obviously odd anyway)...
That is why I did not merge my changes yet. The current change does not really look nicer than what the code gave before IMHO.

**Comment by dg9vh** [comment]
@phl0 just play a bit around - I actually got another job by wife - no time to do some programing, hi.

**Comment by phl0** [comment]
Made another commit to my devel branch:

![bildschirmfoto vom 2017-01-16 21-00-16](https://cloud.githubusercontent.com/assets/7112907/21997425/8ec0b958-dc2f-11e6-9961-fc3bcf835a12.png)

What do you think?

**Comment by dg9vh** [comment]
@phl0 I think, it looks ok :+1:

**Comment by phl0** [comment]
Some more details with two modes.

![bildschirmfoto vom 2017-01-16 23-04-50](https://cloud.githubusercontent.com/assets/7112907/22000577/35cf06c2-dc40-11e6-8f1f-ef62017e02bf.png)

**Comment by m1geo** [comment]
Sorry guys, for some reason, GitHub was not informing me of this conversation. I just made lots of changes and was about to submit a pullrequest, when I saw these comments! Looks like I wasted an hour. 

@phl0 these changes you propose look great! Nice work!

@dg9vh I received emails from a user asking why they couldn't place 'E' at the end of the target for echo. I know this, but, not everyone understands what is going on. Either way, it was just a thought.

Thanks both! :) :+1:

**Comment by phl0** [comment]
Ok then. Thanks for the feedback. I will PR it then.

**Comment by phl0** [comment]
See https://github.com/dg9vh/MMDVMHost-Dashboard/pull/82

**Comment by phl0** [comment]
Closed via 3ef43d7e2cceca89609994c1ccb8d75ef71573c0
